-- Spells
dofile("mods/realistic_particles_fix/files/entities/projectiles/arrow.lua")
dofile("mods/realistic_particles_fix/files/entities/projectiles/black_hole.lua")
dofile("mods/realistic_particles_fix/files/entities/projectiles/bouncy_orb.lua")
dofile("mods/realistic_particles_fix/files/entities/projectiles/bubbleshot.lua")
dofile("mods/realistic_particles_fix/files/entities/projectiles/bullet_heavy.lua")
dofile("mods/realistic_particles_fix/files/entities/projectiles/bullet_slow.lua")
dofile("mods/realistic_particles_fix/files/entities/projectiles/bullet.lua")
dofile("mods/realistic_particles_fix/files/entities/projectiles/chain_bolt.lua")
dofile("mods/realistic_particles_fix/files/entities/projectiles/death_cross_big.lua")
dofile("mods/realistic_particles_fix/files/entities/projectiles/death_cross.lua")
dofile("mods/realistic_particles_fix/files/entities/projectiles/fireball.lua")